In [ ]:
NAME: rohan khatal
ROLL_NO: 13234
BATCH: B2

In [1]:
import pandas as pd

In [9]:
import numpy as np

In [2]:
x = np.array([2, 3, 5, 7, 10])

In [3]:
print(x)

<IntegerArray>
[2, 3, 5, 7, 10]
Length: 5, dtype: Int64


In [4]:
type(x)

pandas.core.arrays.integer.IntegerArray

In [5]:
x=np.array(([2,5,7,10]),dtype="float")

In [6]:
type(x)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [10]:
x = np.zeros((3, 4))

In [11]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
x=np.ones((3,4))

In [13]:
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
x = np.full((3, 4), 9)

In [15]:
print(x)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [16]:
x=np.eye(3,3)

In [17]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
x = np.arange(2, 10, 3)

In [19]:
print(x)

[2 5 8]


In [20]:
x = np.linspace(7, 10, 10)

In [21]:
print(x)

[ 7.          7.33333333  7.66666667  8.          8.33333333  8.66666667
  9.          9.33333333  9.66666667 10.        ]
